export 'package:learn_flutter/screens/home.dart';
export 'package:learn_flutter/screens/counter.dart';
export 'package:learn_flutter/screens/mini_app.dart';
export 'package:learn_flutter/screens/widget_con_function.dart';
export 'package:learn_flutter/componentes/my_card.dart';
export 'package:learn_flutter/screens/card_screen.dart';
export 'package:learn_flutter/screens/contactos_screen.dart';
export 'package:learn_flutter/screens/lista_estatica.dart';
export 'package:learn_flutter/screens/lista_dinamica.dart';